version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
        stdin_open: true # docker run -i
        tty: true        # docker run -t
    redis:
        image: redis
