version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
            - "nfsmountCC:/mnt/3D/"
        depends_on:
            - redis
        stdin_open: true
        tty: true
    redis:
        image: redis
                                  
volumes:
  nfsmountCC:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.2
      device: "192.168.1.2:/volume1/Incoming/3D/"