name: Test Python Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }} 
        SECRET_KEY: ${{ secrets.SECRET_KEY }} 
    - name: MAKE CLEAN
      run:  make clean
    - name: MAKE INSTALL
      run:  make install
    - name: MAKE TEST
      run:  make test
    - name: MAKE CHECK_CODE
      run:  make check_code
    strategy:
      matrix:
        python-version: [3.8, 3.9]
